import { LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { Logo } from './Logo';

const features = [
  { title: 'Smart & Fast', description: 'Instantly generate resume content backed by career-specific metrics and key action verbs.', icon: Sparkles },
  { title: 'ATS-Optimized', description: 'Ensure your resume passes automatic screening filters with structured, machine-readable layouts.', icon: ShieldCheck },
  { title: 'Secure & Private', description: 'Your personal data is encrypted, secure, and stays under your full control.', icon: LockKeyhole },
];

export function BrandPanel() {
  return <section className="brand-panel relative flex min-h-[620px] w-full flex-col overflow-hidden p-6 text-white sm:p-8 lg:max-w-[580px]"><div className="brand-glow brand-glow-one" /><div className="brand-glow brand-glow-two" /><div className="relative z-10 flex flex-1 flex-col"><Logo /><div className="relative mt-7 flex max-w-[481px] flex-col gap-3"><h1 className="text-[32px] font-normal leading-[1.15] sm:text-[38px] sm:leading-[44px]">Build Resumes <span className="text-[#fc4a27]">That Get You</span> Hired.</h1><p className="text-[14px] leading-[21px] text-[#546176]">Create professional, recruiter-approved resumes with intelligent AI recommendations that target the right keywords.</p></div><ul className="relative mt-7 flex max-w-[481px] flex-col gap-3">{features.map(({ title, description, icon: Icon }) => <li className="flex items-start gap-3" key={title}><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-white/[.08] text-white"><Icon className="h-3.5 w-3.5" /></span><div className="flex flex-1 flex-col gap-0.5"><h2 className="text-[14px] font-normal leading-normal">{title}</h2><p className="text-[12px] leading-[17px] text-white/60">{description}</p></div></li>)}</ul><div className="resume-illustration relative mt-auto hidden h-[180px] w-full sm:flex"><div className="resume-back" /><div className="resume-front"><div className="mb-3 flex items-center gap-3"><div className="h-8 w-8 rounded-full bg-gray-100" /><div><div className="h-2 w-20 rounded bg-gray-200" /><div className="mt-1.5 h-1.5 w-10 rounded bg-gray-100" /></div></div><div className="h-px w-full bg-gray-200" /><div className="mt-4 space-y-2"><div className="h-1.5 w-full rounded bg-blue-500" /><div className="h-1.5 w-full rounded bg-blue-300" /><div className="h-1.5 w-24 rounded bg-gray-200" /></div><div className="mt-3 flex items-center justify-between"><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-600">Passed ATS</span><span className="h-4 w-4 rounded-lg bg-emerald-500" /></div></div></div></div></section>;
}
