/*
  # Full Database Setup Migration for user_profiles, profiles, and resumes

  Run this SQL in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)
  to ensure all columns, unique constraints, and RLS policies are configured.
*/

-- ── 1. Create or Update user_profiles Table ───────────────────────────────────
CREATE TABLE IF NOT EXISTS user_profiles (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        text UNIQUE NOT NULL,
  template_id    text DEFAULT 'modern-blue',
  full_name      text DEFAULT '',
  job_title      text DEFAULT '',
  email          text DEFAULT '',
  phone          text DEFAULT '',
  location       text DEFAULT '',
  street_address text DEFAULT '',
  country        text DEFAULT '',
  website        text DEFAULT '',
  profile_image  text DEFAULT '',
  linkedin       text DEFAULT '',
  github         text DEFAULT '',
  summary        text DEFAULT '',
  education      jsonb DEFAULT '[]'::jsonb,
  experience     jsonb DEFAULT '[]'::jsonb,
  projects       jsonb DEFAULT '[]'::jsonb,
  skills         jsonb DEFAULT '[]'::jsonb,
  certifications jsonb DEFAULT '[]'::jsonb,
  languages      jsonb DEFAULT '[]'::jsonb,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);

-- Ensure UNIQUE constraint on user_id if table already existed
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'user_profiles_user_id_key'
  ) THEN
    ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_user_id_key UNIQUE (user_id);
  END IF;
EXCEPTION
  WHEN OTHERS THEN NULL;
END $$;

-- Enable RLS on user_profiles
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Owner policies for user_profiles
DROP POLICY IF EXISTS "user_profiles_select_own" ON user_profiles;
CREATE POLICY "user_profiles_select_own" ON user_profiles FOR SELECT TO authenticated USING (auth.uid()::text = user_id);

DROP POLICY IF EXISTS "user_profiles_insert_own" ON user_profiles;
CREATE POLICY "user_profiles_insert_own" ON user_profiles FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "user_profiles_update_own" ON user_profiles;
CREATE POLICY "user_profiles_update_own" ON user_profiles FOR UPDATE TO authenticated USING (auth.uid()::text = user_id) WITH CHECK (auth.uid()::text = user_id);

DROP POLICY IF EXISTS "user_profiles_delete_own" ON user_profiles;
CREATE POLICY "user_profiles_delete_own" ON user_profiles FOR DELETE TO authenticated USING (auth.uid()::text = user_id);


-- ── 2. Create or Update profiles Table ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL UNIQUE DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  email         text NOT NULL,
  full_name     text,
  avatar_url    text,
  provider      text NOT NULL DEFAULT 'email',
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_profile" ON profiles;
CREATE POLICY "select_own_profile" ON profiles FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_profile" ON profiles;
CREATE POLICY "insert_own_profile" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_profile" ON profiles;
CREATE POLICY "delete_own_profile" ON profiles FOR DELETE TO authenticated USING (auth.uid() = user_id);


-- ── 3. Create or Update resumes Table ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS resumes (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL UNIQUE DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title        text NOT NULL DEFAULT 'My Resume',
  template_key text NOT NULL DEFAULT 'modern-blue',
  resume_data  jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE resumes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "resumes_select_own" ON resumes;
CREATE POLICY "resumes_select_own" ON resumes FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "resumes_insert_own" ON resumes;
CREATE POLICY "resumes_insert_own" ON resumes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "resumes_update_own" ON resumes;
CREATE POLICY "resumes_update_own" ON resumes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "resumes_delete_own" ON resumes;
CREATE POLICY "resumes_delete_own" ON resumes FOR DELETE TO authenticated USING (auth.uid() = user_id);
